# https://unifiedjs.com/explore/package/remark-cli/#example-config-files-json-yaml-js
plugins:
  - - remark-lint-no-dead-urls
    - skipUrlPatterns:
        - https://www.beeminder.com/api/v1/auth_token.json
        - https://www.make.com
        - https://itunes.apple.com
