name: Dead Links
on:
  schedule:
    # Weekly, Mondays at 12:00 UTC
    - cron: "0 12 * * 1"
  workflow_dispatch:
env:
  NODE_VERSION: 20
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Check for dead links
        run: pnpm run lint
