name: Dead Links
on:
  schedule:
    # Weekly, Mondays at 12:00 UTC
    - cron: "0 12 * * 1"
  workflow_dispatch:
permissions:
  contents: read
env:
  NODE_VERSION: 22
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 9
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Check for dead links
        run: pnpm run lint
